controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# the "app_lucky_number" route name is not important yet
#app_lucky_number:
#    path: /lucky/number
#    controller: App\Controller\LuckyController::number